language: ruby
sudo: false
cache: bundler
bundler_args: --without yard guard benchmarks tools
before_script:
  - psql -c 'create database rom_model' -U postgres
script: "bundle exec rake ci"
rvm:
  - 2.1.7
  - 2.2.5
  - 2.3.1
  - rbx-2
  - rbx-3
  - jruby-9.0.5.0
  - jruby-head
  - ruby-head
gemfile:
  - Gemfile.rails-4.2.x
  - Gemfail.rails-5.0.x
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  exclude:
    - rvm: 2.1.7
      gemfile: Gemfile.rails-5.0.x
    - rvm: rbx-2
      gemfile: Gemfile.rails-5.0.x
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
